import { useEffect, useRef, useState } from 'react';
import type { VideoItem } from '../services/api';

interface VideoCardProps { readonly video: VideoItem; readonly muted: boolean; readonly onToggleMuted: () => void; }
function getYouTubeEmbedUrl(url: string, muted: boolean): string { let id: string | null | undefined; try { id = new URL(url).searchParams.get('v'); } catch { id = undefined; } const fallback = id || url.split('/').pop() || ''; return `https://www.youtube-nocookie.com/embed/${fallback}?autoplay=1&mute=${muted ? 1 : 0}&playsinline=1&rel=0`; }
function getTikTokEmbedUrl(url: string): string | undefined { const match = /\/video\/(\d+)/.exec(url); return match ? `https://www.tiktok.com/embed/v2/${match[1]}` : undefined; }
function getFacebookEmbedUrl(url: string): string { return `https://www.facebook.com/plugins/video.php?href=${encodeURIComponent(url)}&show_text=false`; }
function isDirectVideo(url: string): boolean { return /\.(mp4|webm|mov|m3u8)(\?|$)/i.test(url); }

function VideoCard({ video, muted, onToggleMuted }: VideoCardProps) {
  const cardRef = useRef<HTMLElement>(null); const videoRef = useRef<HTMLVideoElement>(null); const [isVisible, setIsVisible] = useState(false); const [isPlaying, setIsPlaying] = useState(false); const [progress, setProgress] = useState(0); const [saved, setSaved] = useState(() => localStorage.getItem(`loop-saved-${video.id}`) === '1');
  const isYouTube = video.source === 'youtube'; const tiktokEmbed = video.source === 'tiktok' && !isDirectVideo(video.videoUrl) ? getTikTokEmbedUrl(video.videoUrl) : undefined; const isFacebookEmbed = video.source === 'facebook' && !isDirectVideo(video.videoUrl); const isEmbed = isYouTube || tiktokEmbed !== undefined || isFacebookEmbed;
  useEffect(() => { const card = cardRef.current; if (!card) return; const observer = new IntersectionObserver(([entry]) => setIsVisible(entry.isIntersecting && entry.intersectionRatio > 0.65), { threshold: [0, 0.65, 1] }); observer.observe(card); return () => observer.disconnect(); }, [isYouTube, tiktokEmbed, isFacebookEmbed]);
  useEffect(() => { if (isEmbed || !videoRef.current) return; if (isVisible) void videoRef.current.play().catch(() => setIsPlaying(false)); else { videoRef.current.pause(); setIsPlaying(false); } }, [isVisible, isEmbed]);
  const toggleSaved = () => { const next = !saved; setSaved(next); localStorage.setItem(`loop-saved-${video.id}`, next ? '1' : '0'); };
  const togglePlayback = () => { if (!videoRef.current || isEmbed) return; if (videoRef.current.paused) void videoRef.current.play().catch(() => undefined); else videoRef.current.pause(); };
  return <article ref={cardRef} className={`video-card ${!isEmbed && !isPlaying ? 'is-paused' : ''}`} aria-label={video.title} onClick={togglePlayback}>
    {isYouTube ? <iframe className="video-player" src={isVisible ? getYouTubeEmbedUrl(video.videoUrl, muted) : undefined} title={video.title} allow="autoplay; encrypted-media; picture-in-picture" allowFullScreen /> : tiktokEmbed ? <iframe className="video-player" src={isVisible ? tiktokEmbed : undefined} title={video.title} allow="autoplay; encrypted-media; picture-in-picture" allowFullScreen /> : isFacebookEmbed ? <iframe className="video-player" src={isVisible ? getFacebookEmbedUrl(video.permalink || video.videoUrl) : undefined} title={video.title} allow="autoplay; encrypted-media; picture-in-picture" allowFullScreen /> : <video ref={videoRef} className="video-player" src={video.videoUrl} poster={video.thumbnailUrl} muted={muted} loop playsInline preload="metadata" onPlay={() => setIsPlaying(true)} onPause={() => setIsPlaying(false)} onLoadedMetadata={(event) => setProgress(event.currentTarget.duration ? (event.currentTarget.currentTime / event.currentTarget.duration) * 100 : 0)} onTimeUpdate={(event) => setProgress(event.currentTarget.duration ? (event.currentTarget.currentTime / event.currentTarget.duration) * 100 : 0)}><track kind="captions" label="Captions" /></video>}
    <div className="video-shade" /><div className={`video-progress ${isEmbed ? 'embed-progress' : ''}`}><span style={{ width: `${isEmbed ? undefined : `${progress}%`}` }} /></div>{!isEmbed && !isPlaying && <button className="play-toggle" onClick={(event) => { event.stopPropagation(); togglePlayback(); }} aria-label="Play video"><span>▶</span></button>}<button className={`audio-button ${muted ? 'is-muted' : 'is-live'}`} onClick={(event) => { event.stopPropagation(); onToggleMuted(); }} aria-label={muted ? 'Turn sound on' : 'Turn sound off'} aria-pressed={!muted} title={muted ? 'Sound off' : 'Sound on'}><span className="audio-icon" aria-hidden="true">{muted ? <svg viewBox="0 0 24 24"><path d="M4 9v6h4l5 4V5L8 9H4Z" /><path d="M17 8.5 22 15.5M22 8.5 17 15.5" /></svg> : <svg viewBox="0 0 24 24"><path d="M4 9v6h4l5 4V5L8 9H4Z" /><path d="M17 9.5a5 5 0 0 1 0 5M19.5 7a8.5 8.5 0 0 1 0 10" /></svg>}</span><span className="audio-label">{muted ? 'Sound off' : 'Sound on'}</span></button><button className={`save-button ${saved ? 'saved' : ''}`} onClick={(event) => { event.stopPropagation(); toggleSaved(); }} aria-label={saved ? 'Remove from saved moments' : 'Save moment'}>{saved ? '♥' : '♡'}</button><div className="video-details"><span className="source-badge">{video.source}</span><h3>{video.title}</h3>{video.author && <p className="author">@{video.author.replace(/^@/, '')}</p>}{video.description && <p className="description">{video.description}</p>}</div>
  </article>;
}
interface VideoFeedProps { readonly videos: VideoItem[]; }
export default function VideoFeed({ videos }: VideoFeedProps) { const [muted, setMuted] = useState(true); const toggleMuted = () => setMuted((current) => !current); if (!videos.length) return <p className="empty-state"><span>⌁</span>No moments match that signal.<small>Try another source or clear your search.</small></p>; return <main className="feed">{videos.map((video) => <VideoCard key={`${video.source}-${video.id}`} video={video} muted={muted} onToggleMuted={toggleMuted} />)}</main>; }
